# Common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker
   
jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-key-which-should-be-changed-in-production-and-be-base64-encoded
    cache:
        ehcache:
            time-to-live-seconds: 1

eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@10.10.252.146:8761/eureka/
    server:
        peer-node-read-timeout-ms: 10000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://10.6.1.117:5432/postgres?currentSchema=dmilog
    username: dmilog
    password: dmilog
    hikari:
      poolName: Hikari
      auto-commit: false
  profiles:
    include:
      swagger, no-liquibase, oracleDB, odbIntCentri, odbIntConti, odbIntFattori, odbIntSegnaliConto

oracle:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@//db_ora001:1521/ORCL.DMPA.ITA
    username: DMICOGE
    password: dmicoge
    auto-commit: false
    hikari:
      auto-commit: false

postgres:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://10.6.1.117:5432/postgres?currentSchema=dmilog
    username: dmilog
    password: dmilog
    auto-commit: false
    hikari:
      poolName: Hikari
      auto-commit: false
  
ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 3
  ReadTimeout: 60000
  ConnectTimeout: 5000

zuul: # those values must be configured depending on the application specific needs
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:postgresql://10.10.252.117:5432/postgres?currentSchema=zschemaprova
#    username: zprova
#    password: zprova
#    hikari:
#      poolName: Hikari
#      auto-commit: false

#spring:
#  data:
#    mongodb:
#      uri: mongodb://prova:prova@10.10.252.164:27017/zprove
#    elasticsearch:
#      rest:
#        uris: http://10.10.252.128:9200


#jhipster:
#    registry:
#        password: admin
