# Common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-key-which-should-be-changed-in-production-and-be-base64-encoded

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@192.168.99.100:8761/eureka/

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://10.6.1.117:5432/postgres?currentSchema=dmilog
    username: dmilog
    password: dmilog
    hikari:
      poolName: Hikari
      auto-commit: false
  profiles:
    include:
      swagger, no-liquibase, oracleDB, odbIntCentri, odbIntConti, odbIntFattori, odbIntSegnaliConto

oracle:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@//db_ora001:1521/ORCL.DMPA.ITA
    username: DMICOGE
    password: dmicoge
    auto-commit: false
    hikari:
      auto-commit: false

postgres:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://10.6.1.117:5432/postgres?currentSchema=dmilog
    username: dmilog
    password: dmilog
    auto-commit: false
    hikari:
      poolName: Hikari
      auto-commit: false
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:postgresql://10.10.252.117:5432/postgres?currentSchema=zschemaprova
#    username: zprova
#    password: zprova
#    hikari:
#      poolName: Hikari
#      auto-commit: false

#spring:
#  data:
#    mongodb:
#      uri: mongodb://prova:prova@10.10.252.164:27017/zprove
#    elasticsearch:
#      rest:
#        uris: http://10.10.252.128:9200
jhipster.cache.ehcache.time-to-live-seconds: 1